In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('D:\ANSON\OpenCV\Computer-Vision-with-Python\DATA\\bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
X = data[:,:-1]
y = data[:,-1]

In [5]:
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [6]:

y

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.preprocessing import MinMaxScaler

scale_object = MinMaxScaler()

In [9]:
scale_object.fit(X_train)

MinMaxScaler()

In [10]:
scale_X_train = scale_object.transform(X_train)
scale_X_test = scale_object.transform(X_test)

In [16]:
scale_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [11]:
from keras.models import Sequential
from keras.layers import Dense

In [17]:
model = Sequential()
model.add(Dense(4, input_dim = 4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [18]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [19]:
model.fit(scale_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 2s - loss: 0.6884 - accuracy: 0.5332
Epoch 2/50
29/29 - 0s - loss: 0.6812 - accuracy: 0.5495
Epoch 3/50
29/29 - 0s - loss: 0.6772 - accuracy: 0.5495
Epoch 4/50
29/29 - 0s - loss: 0.6733 - accuracy: 0.5495
Epoch 5/50
29/29 - 0s - loss: 0.6697 - accuracy: 0.5495
Epoch 6/50
29/29 - 0s - loss: 0.6656 - accuracy: 0.5495
Epoch 7/50
29/29 - 0s - loss: 0.6615 - accuracy: 0.5495
Epoch 8/50
29/29 - 0s - loss: 0.6569 - accuracy: 0.5550
Epoch 9/50
29/29 - 0s - loss: 0.6525 - accuracy: 0.5713
Epoch 10/50
29/29 - 0s - loss: 0.6472 - accuracy: 0.5778
Epoch 11/50
29/29 - 0s - loss: 0.6413 - accuracy: 0.6007
Epoch 12/50
29/29 - 0s - loss: 0.6353 - accuracy: 0.6572
Epoch 13/50
29/29 - 0s - loss: 0.6282 - accuracy: 0.6659
Epoch 14/50
29/29 - 0s - loss: 0.6205 - accuracy: 0.6953
Epoch 15/50
29/29 - 0s - loss: 0.6121 - accuracy: 0.6997
Epoch 16/50
29/29 - 0s - loss: 0.6028 - accuracy: 0.7073
Epoch 17/50
29/29 - 0s - loss: 0.5938 - accuracy: 0.7073
Epoch 18/50
29/29 - 0s - loss: 0.5842 - 

In [20]:
from sklearn.metrics import confusion_matrix, classification_report

In [26]:
predict = model.predict(scale_X_test)
predict[predict >= 0.5] = 1
predict[predict < 0.5] = 0
confusion_matrix(y_test, predict)

array([[251,   6],
       [  9, 187]], dtype=int64)

In [28]:
print(classification_report(y_test, predict))

              precision    recall  f1-score   support

         0.0       0.97      0.98      0.97       257
         1.0       0.97      0.95      0.96       196

    accuracy                           0.97       453
   macro avg       0.97      0.97      0.97       453
weighted avg       0.97      0.97      0.97       453



In [ ]:
model.save('supermodel.h5')

In [ ]:
from keras.models import load_model
model = load_model('supermodel.h5')